# Configures the installation of homebrew packages.
- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    # Utilities
    - tree
    # Programming languages
    - rust
    - go
    - python3
    - nvm
    # Tooling
    - minikube

- name: Install homebrew cask packages 
  homebrew_cask: name={{ item }} state=present
  with_items:
    - docker
    - visual-studio-code
    - spotify
    - discord
    - notion
    - slack
