- name: Link dotfiles
  copy:
    src: "{{ role_path }}/files/{{ item }}"
    dest: "~/{{ item }}"
    force: false
  loop:
  - .gitconfig
  - .zshrc
  - .zprofile

- name: Install homebrew packages
  homebrew: name={{ item }} state=present
  with_items:
    # Utilities
    - tree
    - gnupg
    - bufbuild/buf/buf
    - protobuf
    # Programming languages
    - rust
    - go
    - python3
    - nvm
    # Tooling
    - minikube
    - nvim

- name: Install homebrew cask packages 
  homebrew_cask: name={{ item }} state=present
  with_items:
    - docker
    - visual-studio-code
    - spotify
    - discord
    - notion
    - slack

- name: Generate ED25519 ssh key
  command: ssh-keygen -t ed25519 -a 100 -N "" -C "rojasdiegopro@gmail.com" -f ~/.ssh/id_ed25519
  args:
    creates: ~/.ssh/id_ed25519
